# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, default='', max_length=30)),
                ('last', models.CharField(blank=True, default='', max_length=30)),
                ('tel', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientResultLinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=main.models.directory_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceLinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Feadback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, default='', max_length=30)),
                ('last', models.CharField(blank=True, default='', max_length=30)),
                ('tel', models.CharField(blank=True, default='', max_length=30)),
                ('wish', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Service'),
        ),
        migrations.AddField(
            model_name='clientservicelinker',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Service'),
        ),
        migrations.AddField(
            model_name='clientresultlinker',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Result'),
        ),
        migrations.AddField(
            model_name='client',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='client_result', through='main.ClientResultLinker', to='main.Result'),
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='client_service', through='main.ClientServiceLinker', to='main.Service'),
        ),
    ]
