# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feadback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='feadback',
            name='first',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='feadback',
            name='last',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='feadback',
            name='tel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='feadback',
            name='wish',
            field=models.CharField(max_length=30),
        ),
    ]
