# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170525_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=main.models.portfolio_path)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feadback',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
