# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 11:46
from __future__ import unicode_literals

import dgcrm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, default='', max_length=30)),
                ('last', models.CharField(blank=True, default='', max_length=30)),
                ('tel', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientResultLinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=dgcrm.models.directory_path)),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceLinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='', max_length=30)),
                ('data_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('detailed_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService')),
            ],
        ),
        migrations.CreateModel(
            name='Feadback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('wish', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_event', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='feadback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Feadback'),
        ),
        migrations.AddField(
            model_name='clientresultlinker',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Result'),
        ),
        migrations.AddField(
            model_name='client',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='client_result', through='dgcrm.ClientResultLinker', to='dgcrm.Result'),
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='client_service', through='dgcrm.ClientServiceLinker', to='main.DetailedService'),
        ),
    ]
