# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feadback',
            name='has_event',
        ),
    ]
