# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0002_remove_feadback_has_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='feadback',
            name='has_event',
            field=models.BooleanField(default=False),
        ),
    ]
