# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 13:26
from __future__ import unicode_literals

import dgcrm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0003_feadback_has_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientresultlinker',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientresultlinker',
            name='result',
        ),
        migrations.RemoveField(
            model_name='client',
            name='results',
        ),
        migrations.AddField(
            model_name='result',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client'),
        ),
        migrations.AddField(
            model_name='result',
            name='photo',
            field=models.FileField(blank=True, upload_to=dgcrm.models.directory_path),
        ),
        migrations.DeleteModel(
            name='ClientResultLinker',
        ),
    ]
