# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0004_auto_20170616_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feadback',
            name='wish',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
