# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('dgcrm', '0006_deletedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='', max_length=30)),
                ('data_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('detailed_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService')),
                ('feadback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Feadback')),
            ],
        ),
        migrations.RemoveField(
            model_name='deletedevent',
            name='detailed_service',
        ),
        migrations.RemoveField(
            model_name='deletedevent',
            name='feadback',
        ),
        migrations.DeleteModel(
            name='DeletedEvent',
        ),
    ]
