# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0009_auto_20170626_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField()),
                ('profit', models.IntegerField(blank=True)),
                ('date_time', models.DateTimeField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Event')),
            ],
        ),
    ]
