# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_detailedservice_brutto_price'),
        ('dgcrm', '0010_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEventLinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService')),
            ],
        ),
    ]
