# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0012_auto_20170628_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('в процессе', 'in_progress'), ('успешно', 'successful'), ('неуспешно', 'failed'), ('связаться', 'contact')], default='в процессе', max_length=10),
        ),
    ]
