# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0013_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservicelinker',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientservicelinker',
            name='service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='services',
        ),
        migrations.RemoveField(
            model_name='feadback',
            name='client',
        ),
        migrations.RemoveField(
            model_name='result',
            name='client',
        ),
        migrations.RemoveField(
            model_name='result',
            name='service',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('in_progress', 'ожидается'), ('successful', 'сделано'), ('failed', 'отменился'), ('contact', 'связаться')], default='в процессе', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClientServiceLinker',
        ),
    ]
