# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_detailedservice_brutto_price'),
        ('dgcrm', '0014_auto_20170701_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='event',
        ),
        migrations.RemoveField(
            model_name='result',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='pays',
            field=models.ManyToManyField(blank=True, related_name='pays', to='dgcrm.Pay'),
        ),
        migrations.AddField(
            model_name='event',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='results', to='dgcrm.Result'),
        ),
        migrations.AddField(
            model_name='pay',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client'),
        ),
        migrations.AddField(
            model_name='pay',
            name='detailed_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService'),
        ),
        migrations.AddField(
            model_name='result',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client'),
        ),
        migrations.AddField(
            model_name='result',
            name='detailed_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService'),
        ),
    ]
