# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0015_auto_20170702_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_paid',
        ),
        migrations.AlterField(
            model_name='result',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Client'),
        ),
        migrations.AlterField(
            model_name='result',
            name='detailed_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DetailedService'),
        ),
    ]
