# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0017_remove_event_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='live_in',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='notes',
            field=models.TextField(),
        ),
    ]
