# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0021_auto_20170702_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canceledevent',
            old_name='data_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
