# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0023_auto_20170702_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
