# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0024_auto_20170710_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brutto_price', models.IntegerField()),
                ('customer_price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('UAH', 'грн'), ('USD', 'долл.'), ('EUR', 'евро')], default='грн', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
