# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0025_auto_20170710_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dgcrm.Price'),
        ),
    ]
