# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0026_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
