# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgcrm', '0027_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='brutto_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
