# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_detailedservice_brutto_price'),
        ('dgcrm', '0028_auto_20170712_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detailed_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='detailed_services', to='main.DetailedService'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('in_progress', 'ожидается'), ('successful', 'сделано'), ('failed', 'отменился'), ('contact', 'связаться')], default='in_progress', max_length=20),
        ),
    ]
